"""Deterministic single-commit review primitives."""

from __future__ import annotations

import json
import re
import shlex
import subprocess
from collections.abc import Iterable
from datetime import datetime
from pathlib import Path
from typing import Any

from .commit_artifact import parse_commit_artifact
from .expert_checks import evaluate_commit_checks, render_check_results_text
from .hostile_input import scan_hostile_instruction_texts
from .kernel_impact import kernel_impacts_for_paths

HIGH_RISK_PREFIXES = (
    "arch/",
    "drivers/",
    "fs/",
    "kernel/",
    "mm/",
    "net/",
    "security/",
    "scripts/",
)

CI_STATIC_ANALYSIS_MARKERS = ("ruff", "mypy", "flake8", "pylint", "shellcheck", "clang-tidy")
WARNING_POLICY_MARKERS = ("-Werror", "CONFIG_WERROR", "warnings-as-errors")
GENERATED_PATH_MARKERS = (
    "/generated/",
    "generated/",
    ".generated.",
    "autogenerated",
)
GENERATED_TEXT_MARKERS = (
    "generated by",
    "auto-generated",
    "autogenerated",
    "do not edit",
)
MAX_LINUX_SECURITY_CUE_INPUT_BYTES = 8_192
MAX_LINUX_SECURITY_CUES_PER_FAMILY = 8
LINUX_SECURITY_CUE_PATTERNS = (
    ("cve", re.compile(r"\bCVE-\d{4}-\d{4,}\b", re.IGNORECASE)),
    ("xsa", re.compile(r"\bXSA-\d+\b", re.IGNORECASE)),
    ("fixes", re.compile(r"^Fixes:\s+.+", re.IGNORECASE | re.MULTILINE)),
    ("reported-by", re.compile(r"^Reported-by:\s+.+", re.IGNORECASE | re.MULTILINE)),
    ("reviewed-by", re.compile(r"^Reviewed-by:\s+.+", re.IGNORECASE | re.MULTILINE)),
    ("tested-by", re.compile(r"^Tested-by:\s+.+", re.IGNORECASE | re.MULTILINE)),
    (
        "security-language",
        re.compile(
            r"\b(security[ -]?fix|double[ -]free|buffer[ -]overflow|"
            r"use-after-free|lifetime|VMA|mm)\b",
            re.IGNORECASE,
        ),
    ),
)
PATCH_SECURITY_LANGUAGE_PATTERN = re.compile(
    r"\b(security[ -]?fix|double[ -]free|buffer[ -]overflow|use-after-free|lifetime|VMA)\b",
    re.IGNORECASE,
)


JsonObject = dict[str, Any]


def review_commit(repo: Path | str, commit: str) -> JsonObject:
    """Review one git commit and emit deterministic reviewer-assistance findings."""

    repo_path = Path(repo)
    commit_artifact = parse_commit_artifact(repo_path, commit)
    commit_sha = commit_artifact["commit"]
    subject = commit_artifact["subject"]
    body = commit_artifact["body"]
    name_status = commit_artifact["path_changes"]
    patch = commit_artifact["diff_excerpt"]
    integrity_assessment = _integrity_assessment(repo_path, commit, commit_artifact)

    findings: list[JsonObject] = []
    touched_paths = sorted({path for entry in name_status for path in entry["paths"]})

    deleted_tests = [
        entry["paths"][-1]
        for entry in name_status
        if entry["status"] == "D" and _is_test_path(entry["paths"][-1])
    ]
    if deleted_tests:
        findings.append(
            _finding(
                "removed-test",
                "high",
                "A test file was removed.",
                [f"path:{path}" for path in deleted_tests],
                "Check whether coverage or regression protection was intentionally "
                "replaced elsewhere.",
            )
        )

    ci_paths = [path for path in touched_paths if _is_ci_path(path)]
    if ci_paths and any(marker in patch.lower() for marker in CI_STATIC_ANALYSIS_MARKERS):
        findings.append(
            _finding(
                "ci-static-analysis-weakened",
                "medium",
                "CI or static-analysis configuration changed around known analysis commands.",
                [f"path:{path}" for path in ci_paths],
                "Inspect whether checks were removed, weakened, or moved to another workflow.",
            )
        )

    patch_by_path = _patch_sections_by_path(patch)
    removed_warning_markers = [
        marker
        for marker in WARNING_POLICY_MARKERS
        if any(
            marker in line
            for path, path_patch in patch_by_path.items()
            if _is_warning_policy_path(path)
            for line in _removed_patch_lines(path_patch)
        )
    ]
    if removed_warning_markers:
        findings.append(
            _finding(
                "warning-policy-weakened",
                "medium",
                "Compiler warning policy appears to be weakened.",
                [f"marker:{marker}" for marker in sorted(set(removed_warning_markers))],
                (
                    "Check whether warning enforcement moved elsewhere before "
                    "accepting the relaxation."
                ),
            )
        )

    generated_paths = [
        path
        for path in touched_paths
        if _looks_generated_path(path)
        or _patch_for_path_contains_generated_text(path, patch_by_path)
    ]
    if generated_paths:
        findings.append(
            _finding(
                "generated-code-churn",
                "low",
                "Generated or generated-looking files changed.",
                [f"path:{path}" for path in generated_paths],
                "Confirm generated files can be reproduced from tracked sources and tooling.",
            )
        )

    added_scripts = [
        entry["paths"][-1]
        for entry in name_status
        if entry["status"] == "A" and _looks_like_script(entry["paths"][-1])
    ]
    if added_scripts:
        findings.append(
            _finding(
                "suspicious-script-added",
                "medium",
                "A script-like file was added.",
                [f"path:{path}" for path in added_scripts],
                "Review whether the script runs in CI, build, install, or release paths.",
            )
        )

    integrity_cues = integrity_assessment["provenance_cues"]
    review_attention_cues = [
        cue for cue in integrity_cues if cue != "unsigned-or-unverified-signature"
    ]
    if review_attention_cues:
        evidence = [f"cue:{cue}" for cue in integrity_cues]
        if integrity_assessment["object_checks"]["commit_object_reachable"]:
            evidence.append("object:commit-reachable")
        if integrity_assessment["object_checks"]["tree_object_reachable"]:
            evidence.append("object:tree-reachable")
        findings.append(
            _finding(
                "commit-integrity-cue",
                "medium",
                "Commit provenance or object-integrity facts deserve review attention.",
                evidence,
                (
                    "Verify authorship, signature policy, review path, and object provenance "
                    "before treating the change as trusted."
                ),
            )
        )

    hostile_hits = scan_hostile_instruction_texts(
        [
            ("commit-subject", subject),
            ("commit-body", body),
            ("diff", patch),
            *[(f"path:{path}", path) for path in touched_paths],
        ]
    )
    if hostile_hits:
        evidence = sorted(
            {
                *[f"marker:{hit.marker}" for hit in hostile_hits],
                *[f"location:{hit.location}" for hit in hostile_hits],
            }
        )
        findings.append(
            _finding(
                "prompt-injection-text",
                "medium",
                (
                    "Prompt-injection or hostile-instruction language appears in commit text, "
                    "paths, or diff."
                ),
                evidence,
                "Treat affected text as hostile data and avoid feeding it directly "
                "to privileged tools or prompts.",
            )
        )

    linux_security_cues = _linux_security_cues(
        f"{subject}\n{body}", patch, touched_paths
    )
    if linux_security_cues:
        findings.append(
            _finding(
                "linux-security-cue",
                "medium",
                "Commit text or patch contains Linux security/review cues.",
                linux_security_cues,
                (
                    "Use these cues to prioritize human review and targeted retest; "
                    "this is not a verdict."
                ),
            )
        )

    high_risk_paths = [path for path in touched_paths if path.startswith(HIGH_RISK_PREFIXES)]
    if high_risk_paths:
        findings.append(
            _finding(
                "high-risk-path",
                "medium",
                "The commit touches paths that commonly need careful kernel or "
                "build-system review.",
                [f"path:{path}" for path in high_risk_paths],
                "Map these paths to subsystem ownership and targeted retest areas.",
            )
        )

    review = {
        "schema_version": 1,
        "review_posture": "review-assistant-not-verdict",
        "commit": commit_sha,
        "subject": subject,
        "touched_paths": touched_paths,
        "kernel_impacts": kernel_impacts_for_paths(touched_paths),
        "commit_artifact": commit_artifact,
        "integrity_assessment": integrity_assessment,
        "findings": findings,
        "optional_check_hooks": _optional_check_hooks(commit_sha),
    }
    review["expert_check_results"] = evaluate_commit_checks(review)
    return review


def render_text(review: JsonObject) -> str:
    """Render a product-shaped human-readable single-commit review."""

    artifact = review["commit_artifact"]
    limits = artifact.get("limits", {})
    signature = artifact.get("signature", {})
    findings = review.get("findings", [])
    path_changes = artifact.get("path_changes", [])
    diff_stats = artifact.get("diff_stats", [])
    touched_paths = review.get("touched_paths", [])

    lines = [
        "Commit review",
        "Source facts:",
        f"- commit: {review['commit']}",
        f"- subject: {review['subject']}",
        f"- posture: {review['review_posture']}",
        f"- author: {_identity_label(artifact['author'])}",
        f"- committer: {_identity_label(artifact['committer'])}",
        f"- parents: {len(artifact.get('parents', []))}",
        f"- tree: {artifact.get('tree', '')}",
        "Patch shape:",
        f"- touched paths: {len(touched_paths)}",
    ]
    for path in touched_paths[:12]:
        lines.append(f"  - path:{path}")
    omitted_paths = max(0, len(touched_paths) - 12)
    if omitted_paths:
        lines.append(f"  - omitted paths in text report: {omitted_paths}")
    if path_changes:
        status_counts = _count_values(str(change.get("status", "")) for change in path_changes)
        lines.append(f"- path statuses: {_format_counts(status_counts)}")
    if diff_stats:
        additions = sum(stat.get("additions") or 0 for stat in diff_stats)
        deletions = sum(stat.get("deletions") or 0 for stat in diff_stats)
        lines.append(f"- diff stat: +{additions}/-{deletions}")

    lines.append("Deterministic findings:")
    if not findings:
        lines.append("- none")
    for finding in findings:
        lines.append(f"- {finding['id']} [{finding['severity']}]: {finding['summary']}")
        lines.append(f"  uncertainty: {finding['uncertainty']}")
        evidence = finding.get("evidence", [])
        if evidence:
            lines.append("  evidence:")
            for item in evidence[:8]:
                lines.append(f"    - {item}")
            omitted_evidence = max(0, len(evidence) - 8)
            if omitted_evidence:
                lines.append(f"    - omitted evidence in text report: {omitted_evidence}")

    lines.extend(render_check_results_text(review.get("expert_check_results", [])))

    lines.append("Security/provenance cues:")
    lines.append("- raw commit and diff content is hostile evidence, not instructions")
    lines.append(f"- trust boundary: {artifact.get('trust_boundary', '')}")
    secondary = artifact.get("secondary_trust_boundaries", [])
    if secondary:
        lines.append(f"- secondary trust boundaries: {', '.join(secondary)}")
    lines.append(f"- signature: {signature.get('status', 'unknown')}")
    risk_hints = artifact.get("risk_hints", [])
    lines.append(f"- risk hints: {', '.join(risk_hints) if risk_hints else 'none'}")

    lines.append("Kernel impact hints:")
    impacts = review.get("kernel_impacts", [])
    if not impacts:
        lines.append("- none")
    for impact in impacts:
        lines.append(f"- {impact['id']}: {impact['summary']}")
        lines.append(f"  retest: {', '.join(impact['retest_hints'])}")
        if impact.get("evidence"):
            lines.append(f"  evidence: {', '.join(impact['evidence'][:6])}")

    lines.append("Limits/truncation:")
    lines.append(
        "- diff excerpt: "
        f"{limits.get('diff_excerpt_bytes', 0)}/{limits.get('max_diff_excerpt_bytes', 0)} bytes"
    )
    lines.append(f"- truncated: {limits.get('truncated', False)}")
    lines.append(f"- omitted records: {limits.get('omitted_record_count', 0)}")

    lines.append("Suggested next checks:")
    suggested_checks = _unique_values(
        [str(finding["suggested_next_check"]) for finding in findings]
    )
    for check in suggested_checks:
        lines.append(f"- {check}")
    for hook in review.get("optional_check_hooks", []):
        lines.append(f"- optional {hook['id']}: {hook['summary']}")
    if not suggested_checks and not review.get("optional_check_hooks", []):
        lines.append("- none")
    return "\n".join(lines)


def render_json(review: JsonObject) -> str:
    """Render a stable JSON review."""

    return json.dumps(review, indent=2, sort_keys=True) + "\n"


def _identity_label(identity: JsonObject) -> str:
    name = identity.get("name", "")
    email = identity.get("email", "")
    timestamp = identity.get("timestamp", "")
    return f"{name} <{email}> {timestamp}"


def _count_values(values: Iterable[str]) -> dict[str, int]:
    counts: dict[str, int] = {}
    for value in values:
        counts[value] = counts.get(value, 0) + 1
    return counts


def _format_counts(counts: dict[str, int]) -> str:
    return ", ".join(f"{key}={counts[key]}" for key in sorted(counts))


def _unique_values(values: list[str]) -> list[str]:
    seen: set[str] = set()
    unique: list[str] = []
    for value in values:
        if value in seen:
            continue
        seen.add(value)
        unique.append(value)
    return unique


def _integrity_assessment(repo: Path, review_input: str, artifact: JsonObject) -> JsonObject:
    commit = str(artifact["commit"])
    tree = str(artifact["tree"])
    object_checks = {
        "commit_object_reachable": _git_object_exists(repo, f"{commit}^{{commit}}"),
        "tree_object_reachable": _git_object_exists(repo, f"{tree}^{{tree}}"),
    }
    provenance_cues: list[str] = []
    author = artifact["author"]
    committer = artifact["committer"]
    if (author.get("name"), author.get("email")) != (
        committer.get("name"),
        committer.get("email"),
    ):
        provenance_cues.append("author-committer-identity-differs")
    if _timestamp_gap_days(author.get("timestamp", ""), committer.get("timestamp", "")) >= 30:
        provenance_cues.append("author-committer-timestamp-gap")
    signature = artifact.get("signature", {})
    if signature.get("status") != "verified":
        provenance_cues.append("unsigned-or-unverified-signature")
    if not object_checks["commit_object_reachable"]:
        provenance_cues.append("commit-object-unreachable")
    if not object_checks["tree_object_reachable"]:
        provenance_cues.append("tree-object-unreachable")
    return {
        "artifact_type": "integrity_assessment",
        "schema_version": 1,
        "id": f"integrity:{commit}",
        "commit": commit,
        "review_input": review_input,
        "resolved_commit": commit,
        "tree": tree,
        "signature": signature,
        "object_checks": object_checks,
        "provenance_cues": provenance_cues,
        "evidence_refs": [f"git:commit:{commit}", f"git:tree:{tree}"],
        "trust_boundary": "derived_review_signal",
        "uncertainty": "deterministic-facts-with-heuristic-cues",
    }


def _timestamp_gap_days(first: str, second: str) -> int:
    try:
        first_dt = datetime.fromisoformat(first.replace("Z", "+00:00"))
        second_dt = datetime.fromisoformat(second.replace("Z", "+00:00"))
    except ValueError:
        return 0
    return abs((second_dt - first_dt).days)


def _git_object_exists(repo: Path, object_name: str) -> bool:
    completed = subprocess.run(
        ["git", "cat-file", "-e", object_name],
        cwd=repo,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        check=False,
    )
    return completed.returncode == 0


def _git(repo: Path, *args: str) -> str:
    completed = subprocess.run(
        ["git", *args],
        cwd=repo,
        check=True,
        text=True,
        capture_output=True,
    )
    return completed.stdout


def _parse_name_status(raw: str) -> list[JsonObject]:
    entries: list[JsonObject] = []
    for line in raw.splitlines():
        if not line.strip():
            continue
        parts = line.split("\t")
        status = parts[0][0]
        entries.append({"status": status, "paths": parts[1:]})
    return entries


def _finding(
    finding_id: str,
    severity: str,
    summary: str,
    evidence: list[str],
    suggested_next_check: str,
) -> JsonObject:
    return {
        "id": finding_id,
        "severity": severity,
        "summary": summary,
        "evidence": evidence,
        "evidence_refs": evidence,
        "uncertainty": "heuristic",
        "false_positive_caveat": (
            "Heuristic cue only, not proof of a regression or malicious change."
        ),
        "suggested_next_check": suggested_next_check,
    }


def _optional_check_hooks(commit_sha: str) -> list[JsonObject]:
    return [
        {
            "id": "compiler-warning-delta",
            "status": "available-when-configured",
            "summary": "Compare compiler warning output before and after the change.",
            "evidence_refs": [f"commit:{commit_sha}"],
            "trust_boundary": "derived_review_signal",
        },
        {
            "id": "static-analyzer-delta",
            "status": "available-when-configured",
            "summary": "Compare static analyzer findings before and after the change.",
            "evidence_refs": [f"commit:{commit_sha}"],
            "trust_boundary": "derived_review_signal",
        },
        {
            "id": "generated-artifact-reproducibility",
            "status": "available-when-configured",
            "summary": "Rebuild generated artifacts and compare them with committed output.",
            "evidence_refs": [f"commit:{commit_sha}"],
            "trust_boundary": "derived_review_signal",
        },
        {
            "id": "binary-artifact-comparison",
            "status": "available-when-configured",
            "summary": "Compare binary artifacts against trusted rebuilds or prior releases.",
            "evidence_refs": [f"commit:{commit_sha}"],
            "trust_boundary": "derived_review_signal",
        },
    ]


def _linux_security_cues(
    metadata_text: str, patch_text: str, touched_paths: list[str]
) -> list[str]:
    metadata_excerpt, metadata_truncated = _bounded_text(
        metadata_text, MAX_LINUX_SECURITY_CUE_INPUT_BYTES
    )
    patch_excerpt, patch_truncated = _bounded_text(patch_text, MAX_LINUX_SECURITY_CUE_INPUT_BYTES)

    matches_by_id: dict[str, list[str]] = {}
    truncated_families: set[str] = set()
    for cue_id, pattern in LINUX_SECURITY_CUE_PATTERNS:
        _collect_limited_matches(
            cue_id,
            pattern,
            metadata_excerpt,
            matches_by_id,
            truncated_families,
        )
    _collect_limited_matches(
        "security-language",
        PATCH_SECURITY_LANGUAGE_PATTERN,
        patch_excerpt,
        matches_by_id,
        truncated_families,
    )

    has_linux_path = any(path.startswith(HIGH_RISK_PREFIXES) for path in touched_paths)
    strong_cues = matches_by_id.get("cve", []) + matches_by_id.get("xsa", [])
    metadata_cues = [
        cue
        for cue_id, cues in matches_by_id.items()
        if cue_id in {"fixes", "reported-by", "reviewed-by", "tested-by"}
        for cue in cues
    ]
    security_language = matches_by_id.get("security-language", [])
    meaningful_security_language = [
        cue for cue in security_language if cue.lower() != "security-language:mm"
    ]
    if not strong_cues and not (has_linux_path and (meaningful_security_language or metadata_cues)):
        return []

    evidence: list[str] = []
    seen: set[str] = set()
    for cue_id, _pattern in LINUX_SECURITY_CUE_PATTERNS:
        if cue_id not in {"cve", "xsa"} and not has_linux_path:
            continue
        for cue in matches_by_id.get(cue_id, []):
            if cue not in seen:
                seen.add(cue)
                evidence.append(cue)
    if metadata_truncated or patch_truncated or truncated_families:
        evidence.append("limit:linux-security-cue-scan-truncated")
    return evidence


def _collect_limited_matches(
    cue_id: str,
    pattern: re.Pattern[str],
    text: str,
    matches_by_id: dict[str, list[str]],
    truncated_families: set[str],
) -> None:
    for match in pattern.finditer(text):
        family_matches = matches_by_id.setdefault(cue_id, [])
        if len(family_matches) >= MAX_LINUX_SECURITY_CUES_PER_FAMILY:
            truncated_families.add(cue_id)
            return
        snippet = " ".join(match.group(0).split())
        evidence = f"{cue_id}:{snippet}"
        if evidence not in family_matches:
            family_matches.append(evidence)


def _bounded_text(text: str, max_bytes: int) -> tuple[str, bool]:
    encoded = text.encode()
    if len(encoded) <= max_bytes:
        return text, False
    return encoded[:max_bytes].decode(errors="ignore"), True


def _is_test_path(path: str) -> bool:
    lowered = path.lower()
    return lowered.startswith("test/") or lowered.startswith("tests/") or "/test" in lowered


def _is_ci_path(path: str) -> bool:
    lowered = path.lower()
    return lowered.startswith(".github/workflows/") or lowered in {
        ".gitlab-ci.yml",
        "azure-pipelines.yml",
        "tox.ini",
        "pyproject.toml",
    }


def _is_warning_policy_path(path: str) -> bool:
    lowered = path.lower()
    name = Path(lowered).name
    return (
        name in {"makefile", "kbuild", "kconfig", "cmakelists.txt"}
        or lowered.endswith((".mk", ".mak", ".cmake"))
        or _is_ci_path(path)
    )


def _looks_generated_path(path: str) -> bool:
    lowered_path = path.lower()
    return any(marker in lowered_path for marker in GENERATED_PATH_MARKERS)


def _patch_for_path_contains_generated_text(path: str, patch_by_path: dict[str, str]) -> bool:
    lowered_patch = patch_by_path.get(path, "").lower()
    return any(marker in lowered_patch for marker in GENERATED_TEXT_MARKERS)


def _removed_patch_lines(patch: str) -> list[str]:
    """Return removed hunk lines without diff metadata headers."""

    return [
        line[1:]
        for line in patch.splitlines()
        if line.startswith("-") and not line.startswith("--- ")
    ]


def _patch_sections_by_path(patch: str) -> dict[str, str]:
    """Map each file path in a unified git diff excerpt to its own bounded section."""

    sections: dict[str, list[str]] = {}
    current_section: list[str] = []
    for line in patch.splitlines():
        if line.startswith("diff --git "):
            _record_patch_section(sections, current_section)
            current_section = [line]
            continue
        if current_section:
            current_section.append(line)
    _record_patch_section(sections, current_section)
    return {path: "\n".join(lines) for path, lines in sections.items()}


def _record_patch_section(sections: dict[str, list[str]], section_lines: list[str]) -> None:
    if not section_lines:
        return
    section = "\n".join(section_lines)
    for path in _paths_from_patch_section(section_lines):
        existing = sections.setdefault(path, [])
        if existing:
            existing.append("")
        existing.append(section)


def _paths_from_patch_section(section_lines: list[str]) -> list[str]:
    paths: list[str] = []
    for line in section_lines:
        if line.startswith(("--- ", "+++ ")):
            path = _path_from_file_header(line[4:])
            if path and path not in paths:
                paths.append(path)
    if paths:
        return paths
    return _paths_from_diff_git_line(section_lines[0])


def _path_from_file_header(raw_path: str) -> str | None:
    path = _first_git_header_token(raw_path)
    if path in {"", "/dev/null"}:
        return None
    if path.startswith(("a/", "b/")):
        return path[2:]
    return path


def _first_git_header_token(raw_path: str) -> str:
    stripped = raw_path.strip()
    if not stripped:
        return ""
    if stripped.startswith('"'):
        try:
            parsed = shlex.split(stripped)
        except ValueError:
            return ""
        return parsed[0] if parsed else ""
    return stripped.split("\t", maxsplit=1)[0]


def _paths_from_diff_git_line(line: str) -> list[str]:
    prefix = "diff --git "
    if not line.startswith(prefix):
        return []
    raw_paths = line.removeprefix(prefix)
    if raw_paths.startswith('"'):
        try:
            parts = shlex.split(raw_paths)
        except ValueError:
            return []
        return _normalize_diff_git_paths(parts)
    if not raw_paths.startswith("a/") or " b/" not in raw_paths:
        return []
    old_path, new_path = raw_paths.rsplit(" b/", maxsplit=1)
    return _normalize_diff_git_paths([old_path, f"b/{new_path}"])


def _normalize_diff_git_paths(raw_paths: list[str]) -> list[str]:
    paths: list[str] = []
    for raw_path in raw_paths[:2]:
        if raw_path.startswith(("a/", "b/")):
            path = raw_path[2:]
            if path != "/dev/null" and path not in paths:
                paths.append(path)
    return paths


def _looks_like_script(path: str) -> bool:
    lowered = path.lower()
    return lowered.startswith("scripts/") or lowered.endswith((".sh", ".bash", ".py", ".pl", ".rb"))
